---
on:
  push:
    branches:
    - actions-release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    env:
      MB_PYTHON_VERSION: '${{ matrix.python-version }}'
      PLAT: '${{ matrix.platform }}'
      REPO_DIR: bezier
      BUILD_COMMIT: 2d878a2256158648601dc7b45cee74d9aa5b9b7a
      BUILD_DEPENDS: "numpy"
      TEST_DEPENDS: "--requirement bezier/scripts/requirements.txt"
      UNICODE_WIDTH: 32
      MB_ML_VER: 2010
      ENV_VARS_PATH: "travis/env_vars.sh"
      CONFIG_PATH: "travis/config.sh"
      GITHUB_ACTIONS_RUNS_ON: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - macos-latest
        - ubuntu-20.04
        python-version:
        - '3.7'
        - '3.8'
        - '3.9'
        platform:
        - x86_64
        - i686
        - aarch64
        exclude:
        - os: macos-latest
          platform: i686
        - os: macos-latest
          platform: aarch64
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - uses: docker/setup-qemu-action@v1
      if: ${{ matrix.platform == 'aarch64' }}
      name: Set up QEMU
    - name: Set environment variable for aarch64
      if: ${{ matrix.platform == 'aarch64' }}
      run: |
        echo "DOCKER_TEST_IMAGE=$(echo multibuild/xenial_arm64v8)" >> $GITHUB_ENV
        echo "MB_ML_VER="2014" >> $GITHUB_ENV
    - name: Install `gcc`
      run: |
        brew install gcc
        brew unlink gcc
        brew link gcc
    - name: Run "full" set of commands from `.travis.yml`
      run: travis/full.sh
    - name: Upload everything in the wheelhouse
      uses: actions/upload-artifact@v2
      with:
        name: wheelhouse
        path: wheelhouse
